language: cpp
sudo: required
matrix:
  include:
    - dist: bionic
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - sdl2
            - ninja
            - cmake
            - opencv
          update: true
      script:
        - ./install.sh update
install:
  eval "${MATRIX_EVAL}"
script:
  - ./install.sh dl
