language: cpp
sudo: required
matrix:
  include:
    - dist: bionic
      before_install:
        - sudo apt-get update && sudo apt-get install -y cmake ninja-build libsdl2-dev libopencv* libavdevice-dev
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - sdl2
            - ninja
            - cmake
            - opencv
          update: true
install:
  eval "${MATRIX_EVAL}"
script:
  - PROJECT_ROOT=pwd
  - cat CMakeLists.txt
  - mkdir -p tmp
  - cd tmp
  - cmake -G Ninja ..
  - ninja install
  - cd ..